name: Deploy

on:
  push:
    btanches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: test ssh connection
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: root
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          # source: "."
          # target: "/var/www/t-tauri/"
          script: |
            whoami
