name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: test2 ssh connection
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          # source: "."
          # target: "/var/www/t-tauri/"
          script: |
            cd /home
            echo 'Entering test5'
            mkdir test2
            echo 'test 2'
            cd test2
            touch test2.txt
            # git pull
            # echo 'Repository has been pulled'
            # systemctl restart test
            # echo 'test restarted'
          # script: |
          #   whoami
