name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: "3.9.5"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - uses: actions/checkout@v1

      - name: test2 ssh connection
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: "/home/test2/"
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          PORT: ${{ secrets.PORT }}
          script: sh /home/test2/command.sh
