name: Test and Deploy

on: push
jobs:

  deploy:
    #needs: run-test
    runs-on: ubuntu-20.04
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/winc-cd
            echo 'Entering /home/winc-cd directory'
            git pull
            echo 'Repository has been pulled'
            systemctl restart winc-cd
            echo 'winc-cd restarted'

 
